version: '3.8'

services:
  nginx-template:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/var/www/html/client
    depends_on:
      - server-template
    networks:
      - template

  server-template:
    build: ./server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./server:/app
      - /app/vendor/
    networks:
      - template

  mysql-template:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  template:
    driver: bridge
